### ISSUE TITLE
not disassemble properly

### ISSUE THREAD

**Issue by mmcflash** [c4ashley/ghidra-h8-500#1]
![ghidra_h8](https://github.com/user-attachments/assets/543982bf-ae37-4437-801e-bd65d7fb6b34)
![IDA_h8](https://github.com/user-attachments/assets/5407e0ba-086e-4af6-bb14-2ef1aa135d26)
Can you add some instructions ?

**Comment by c4ashley** [comment]
![1732868913_grim](https://github.com/user-attachments/assets/b8920b9e-018a-4827-bf11-0e48955f8be9)

Done!

Thanks for posting a valid IDA disassembly with it. :-)

I can't find any evidence in the manuals that the 8-bit immediate gets zero-extended. If it gets sign-extended, or if it only compares the low 8 bits or something (IDA says it's a 16-bit immediate, so that suggests this isn't the case), the logic flow in the decompilation may be inaccurate. I'll have to run some test code on a chip if I get a chance.
